### ISSUE TITLE
Support for Replication Protocol Version 2

### ISSUE THREAD

**Issue by 3n0ugh** [Trendyol/go-pq-cdc#2]
## Feature Request: Support for Replication Protocol Version 2

**Is your feature request related to a problem? Please describe.**

Currently, the `go-pq-cdc` library supports only replication protocol version 3. This limits its use to PostgreSQL server versions 15 and above. Introducing support for replication protocol version 2 would enable `go-pq-cdc` to function with PostgreSQL server version 14 as well, thus expanding its compatibility.

**Describe the solution you'd like**

Implement conditional handling for replication protocols based on the PostgreSQL server version:

1. **After establishing a connection**, determine the PostgreSQL server version.
   - If the server version is 15 or higher, continue using replication protocol version 3.
   - If the server version is between 14 and 15 (inclusive of 14), switch to using replication protocol version 2.
   - For any server version below 14, return an error indicating that the PostgreSQL version is unsupported.

By adding this logic, `go-pq-cdc` can support a wider range of PostgreSQL versions while ensuring appropriate protocol compatibility.

**Sources**

**Protocol Versions:** https://www.postgresql.org/docs/current/protocol-logical-replication.html#:~:text=Version%202%20is%20supported%20only,streaming%20of%20two%2Dphase%20commits.

**go-pq-cdc protocol choose**: https://github.com/Trendyol/go-pq-cdc/blob/0076edc7cd417a7fc156bbac60c340def151bb1d/pq/replication/replication.go#L27

```[tasklist]
### Tasks
- [ ] Add PostgreSQL version control
- [ ] Set dynamically replication protocol version by PostgreSQL server version
- [ ] Update integration test for PostgreSQL Server version 14 too
- [ ] Update README.md
- [ ] Update go-pq-cdc-elasticsearch go-pq-cdc version and README.md and production_tutorial docs.
```
